187121440 materials bulk upload
cs169/snapcon pull request #28
Opened 2024-03-19 01:48 UTC by warrenlet

### [Pivotal Tracker Link][tracker]

[tracker]: https://www.pivotaltracker.com/story/show/your-story-id

## What this PR does:

This pull request fixes|implements (pick one...) ______.

### Include screenshots, videos, etc.

#### Who authored this PR?

### How should this PR be tested?

* Is there a deploy we can view?
* What do the specs/features test?
* Are there edge cases to watch out for?

#### Are there any complications to deploying this?

### Checklist:

- [ ] Has this been deployed to a staging environment or reviewed by a customer?
- [ ] Tag someone for code review (either a coach / team member)
- [ ] I have renamed the branch to match PivotTracker's suggested one (necessary for BlueJay)

2024-04-01 18:41 UTC, Edge7481 commented
Would it be possible to write a few tests that checks the csv is working

2024-04-04 10:09 UTC, fp456 requested changes
Wondering if it'll be possible to add some tests for the code added. Also, please update the PR template with the given info, thank you!

2024-04-05 00:16 UTC, cycomachead commented on app/views/admin/events/index.html.haml
> +                2,title,https://vimeo.com/myvideo
```suggestion
                1,Session Recording,https://youtube.com/myvideo
                2,Demo Video,https://vimeo.com/myvideo
```

2024-04-08 17:55 UTC, fp456 approved these changes

2024-04-15 22:06 UTC, merged